networks:
  digital-document:
    name: digital-document-network

services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: root
      POSTGRES_DB: digital_document
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - digital-document
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d digital_document"]
      interval: 5s
      timeout: 3s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: minio-digital-document
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio-data:/data
    networks:
      - digital-document
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 3s
      retries: 10

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - digital-document
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 minio minio123 --api s3v4;
      /usr/bin/mc mb --ignore-existing local/employee-documents;
      /usr/bin/mc anonymous set download local/employee-documents;
      echo 'Bucket employee-documents ready';
      "

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local
