spring:
  application:
    name: prueba-back-snk-digital-document
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_PREFIX}${DATABASE_URL}/${DATABASE_NAME}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${DATABASE_SCHEMA}
      poolName: SpringBootJPAHikariCP
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      initializationFailTimeout: 0
  jpa:
    properties:
      hibernate:
        timezone:
          default_storage: NORMALIZE
  flyway:
    locations: classpath:migration/versions
    schemas: ${DATABASE_SCHEMA}

fwkcna:
  kafka:
    enabled: true
    consumer:
      interceptor-default-enabled: true
      topics:
        groups:
          employee:
            main: ${KAFKA_TOPIC_EMPLOYEE:thirdparty.employee.employee.event.public.v0.table.cpd}
            groupId: ${KAFKA_GROUP_ID_EMPLOYEE:thirdparty_employee_employee_prueba-back-snk-digital-document}
      error-type: NONE

outbox:
  topic:
    employee-digital-document: ${KAFKA_TOPIC_OUTPUT:thirdparty.employee.employeedigitaldocument.event.restrictedout.v0.table.cpd}
  publisher:
    delay-ms: ${OUTBOX_PUBLISHER_DELAY_MS:5000}
  jpa:
    repository:
      datasource:
        startup-connectivity-check: false

clients:
  certification:
    url: ${CERTIFICATION_API_BASE_PATH:http://localhost:8081}
    connect-timeout-ms: ${CERTIFICATION_CONNECT_TIMEOUT_MS:3000}
    read-timeout-ms: ${CERTIFICATION_READ_TIMEOUT_MS:5000}

storage:
  bucket-id: ${STORAGE_BUCKET_ID:employee-documents}

fwkcna:
  buckets:
    - id: ${STORAGE_BUCKET_ID:employee-documents}
      bucket-name: ${BUCKET_NAME:employee-documents}
      enabled: true
      provider: ${BUCKET_PROVIDER:minio}
      url: ${BUCKET_URL:http://localhost:9000}
      credentials:
        access-key: ${BUCKET_ACCESS_KEY:minio}
        secret-key: ${BUCKET_SECRET_KEY:minio123}

resilience4j:
  retry:
    instances:
      certificationClient:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - com.mercadona.prueba.snk.digitaldocument.domain.exception.CertificationClientException
        ignore-exceptions:
          - com.mercadona.prueba.snk.digitaldocument.domain.exception.EmployeeNotFoundException

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [info, health, metrics, prometheus]

server:
  port: 8080
