spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_document
    username: sa
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: digital_document
      poolName: SpringBootJPAHikariCP
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      initializationFailTimeout: -1

  flyway:
    locations: classpath:migration/versions
    schemas: digital_document
    create-schemas: true

  kafka:
    bootstrap-servers: localhost:29092
    properties:
      "[schema.registry.url]": http://localhost:9081
      "[security.protocol]": PLAINTEXT
    consumer:
      bootstrap-servers: localhost:29092
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        auto.offset.reset: latest
        "[schema.registry.url]": http://localhost:9081
        "[security.protocol]": PLAINTEXT
    listener:
      ack-mode: manual

  jpa:
    hibernate:
      ddl-auto: none

fwkcna:
  kafka:
    enabled: true
    consumer:
      interceptor-default-enabled: true
      error-type: NONE
  outbox:
    enabled: true
    table-name: o_outbox
    schema-registries:
      sr-basic:
        url: http://localhost:9081
        authentication:
          basic:
            user: ""
            password: ""
  buckets:
    - id: employee-documents
      bucket-name: employee-documents
      enabled: true
      provider: minio
      url: http://localhost:9000
      trust-all-certs: true
      relax-hostname: true
      virtual-host-buckets: false
      signed-operation-token-expiration: 120
      credentials:
        access-key: minio
        secret-key: minio123

clients:
  certification:
    url: http://localhost:8081

outbox:
  topic:
    employee-digital-document: thirdparty.employee.employeedigitaldocument.event.restrictedout.v0.table.cpd
