spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_document
    username: sa
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: digital_document
      initializationFailTimeout: -1
  flyway:
    locations: classpath:migration/versions
    schemas: digital_document
    create-schemas: true

fwkcna:
  kafka:
    consumer:
      topics:
        input-0: thirdparty.employee.employee.event.public.v0.table.cpd
        groupid-0: thirdparty_employee_employee_prueba-back-snk-digital-document
  buckets:
    - id: employee-documents
      bucket-name: employee-documents
      enabled: true
      provider: minio
      url: http://localhost:9000
      trust-all-certs: true
      relax-hostname: true
      virtual-host-buckets: false
      signed-operation-token-expiration: 120
      credentials:
        access-key: minio
        secret-key: minio123

clients:
  certification:
    url: http://localhost:8081
